#include <WinSock2.h>
#include <Windows.h>
#include <iostream>
#include "taglib/fileref.h"
#include "taglib/tag.h"
#include "taglib/tpropertymap.h"
#include <dirent.h>
#include <memory>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <cstdint>
#include <list>